---
- name: Sets Consul arch -> linux_amd64
  set_fact:
    arch: linux_amd64
  when: ansible_system == "Linux"

- name: Sets Consul arch -> darwin_amd64
  set_fact:
    arch: darwin_amd64
  when: ansible_system == "Darwin"

- name: Setup dnsmasq config file
  template:
    src="../templates/dnsmasq-10-consul.j2"
    dest="{{ dnsmasq.config_file }}"
  sudo: yes
  tags:
    - dnsmasq
    - consul
    - install
    - config

- name: Ensure consul group exists
  group:
    name=consul
    state=present
  sudo: yes
  tags:
    - setup
    - consul

- name: Ensure consul user exists
  user:
    name="consul"
    group="consul"
    uid="1050"
    generate_ssh_key=true
    ssh_key_bits=2048
    ssh_key_file=".ssh/id_rsa"
  sudo: yes
  tags:
    - hashicorp
    - consul
    - install
    - setup

- name: Creates configuration directories
  file:
    path="{{ item }}"
    owner={{ consul.user | default('root') }}
    group={{ consul.user  | default('staff') }}
    mode=755
    state=directory
  sudo: yes
  with_items:
    - "{{ consul.dirs }}"
  tags:
    - hashicorp
    - consul
    - install
    - setup

- name: Downloads Packages
  get_url: >
    url="{{ item.url }}"
    dest="{{ item.dest }}"
    mode=0755
    force="{{ consul.install.force_download }}"
  sudo: no
  tags:
    - hashicorp
    - consul
    - install
    - download
  with_items:
    - {"url" : "{{ consul.install.download_location }}/{{ consul.version }}_{{ arch }}.zip" , "dest": "/tmp/{{ consul.version }}_{{ arch }}.zip" }
    - {"url" : "{{ consul.install.download_location }}/{{ consul.version }}_web_ui.zip" , "dest": "/tmp/{{ consul.version }}_web_ui.zip" }

- name: Unpacks to location
  unarchive: >
    src="{{ item.url }}"
    dest="{{ item.dest }}"
    copy=no
    mode=755
    creates=yes
  sudo: yes
  tags:
    - hashicorp
    - consul
    - install
    - unarchive
  with_items:
    - { "url" : "/tmp/{{ consul.version }}_{{ arch }}.zip", "dest" : "{{ consul.install.dir }}" }
    - { "url" : "/tmp/{{ consul.version }}_web_ui.zip", "dest" : "/tmp/consul_ui" }

- name: Moves UI to location
  file:
    dest="{{ consul.ui_dir }}"
    src="/tmp/consul_ui/dist"
    state=link
    owner={{ consul.user }}
    group={{ consul.group }}
  sudo: yes
  tags:
    - ui
    - consul
    - install

- name: Fix permissions on files (Workaround while waiting for 2.0)
  file: path="{{ consul.install.dir }}/{{ item }}"
    owner="{{ consul.user | default('root') }}"
    group="{{ consul.user | default('staff') }}"
    mode=755
  sudo: yes
  with_items:
    - "{{ consul.install.file_list }}"
  tags:
    - hashicorp
    - consul
    - install
    - workaround

- name: Setup consul config @ bootstrap box
  when: "'consul-bootstrap' in {{ group_names }}"
  template:
    src="../templates/consul-bootstrap.json.j2"
    dest="{{ consul.config.dir }}/config.json"
    force=yes
    owner={{ consul.user }}
    group={{ consul.group }}
  sudo: yes
  register: bootstrap_obj
  tags:
    - consul
    - setup
    - config

- name: Setup consul config @  server boxes
  when: "'consul-servers' in {{ group_names }} and 'consul-bootstrap' not in {{ group_names }}"
  template:
    src="../templates/consul-server.json.j2"
    dest="{{ consul.config.dir }}/config.json"
    force=yes
    owner={{ consul.user }}
    group={{ consul.group }}
  sudo: yes
  tags:
    - consul
    - setup
    - config

- name: Setup consul config @ client boxes
  when: "'consul-clients' in {{ group_names }}"
  template:
    src="../templates/consul-client.json.j2"
    dest="{{ consul.config.dir }}/config.json"
    force=yes
    group={{ consul.group }}
    owner={{ consul.user }}
  sudo: yes
  tags:
    - consul
    - setup
    - config

- name: Setup consul service config file
  template:
    src="../templates/consul.conf.j2"
    dest="{{ consul.config.service_file }}"
    owner=root
    group=root
  sudo: yes
  tags:
    - consul
    - setup
    - config

- name: Setup dnsmasq and consul as service
  service:
    name="{{ item }}"
    state=started
  sudo: yes
  tags:
    - dnsmasq
    - service
    - consul
    - config
  with_items:
    - dnsmasq
    - consul

# - name: Deploy Consul Service Definition
#   template:
#     src="{{ item.path }}"
#     dest="{{ consul.config.dir }}"
#     force=yes
#     owner={{ consul.user }}
#     group={{ consul.group }}
#   with_items: consul_services
#   notify: restart consul
#   tags:
#     - service
#     - consul
#     - config
